image: node

stages:
  - build
  - test
  - deploy

build site:
  stage: build
  artifacts:
    paths:
      - website/build/course-gitlab-ci-cd
  script:
    - cd website
    - npm install
    - npm build
