image: node

stages:
  - build
  - test
  - deploy

# Cache for all jobs (don't be confused with "ARTIFACTS"). This cache
# is used between the jobs.
cache:
  paths:
    - ./website/build/course-gitlab-ci-cd

build site:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    # Always export files (even if job fails. Values are: on_success, on_failure, always)
    when: always
    # Expire cache time (from export) - Default 30 days
    expire_in: 2 hrs
    paths:
      - website/build/course-gitlab-ci-cd
  script:
    - cd website
    - npm install
    - npm run build

deploy website:
  stage: deploy
  script:
    - npm install -g surge
    - surge --project ./website/build/course-gitlab-ci-cd/ --domain marcellocosta.surge.sh
