image: node

stages:
  - test
  - package
  - deploy

# Cache for all jobs (don't be confused with "ARTIFACTS"). This cache
# is used between the jobs.
#cache:
#  paths:
#    - ./website/build/course-gitlab-ci-cd

# Global before EACH scripts
before_script:
  - whoami
  - pwd

test site:
  stage: test
  before_script:
    - npm install -g broken-link-checker@^0.7.8 wait-on@^5.2.1
  script:
    - npm install
    - cd website
    - npm install
    - npm run start &
    - cd .. && npm run test
    - blc --recursive --exclude-external --input http://localhost:3000 website

vunerabilities check:
  stage: test
  script:
    - npm install && npm run scan

package site:
  stage: package
  cache:
    key: site-package
    policy: push # Don't download cache and push change to be used by the next steps
    paths:
      - ./website/build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    # Always export files (even if job fails. Values are: on_success, on_failure, always)
    when: always
    # Expire cache time (from export) - Default 30 days
    expire_in: 2 hrs
    paths:
      - website/build/course-gitlab-ci-cd
  script:
    - cd website
    - npm install
    - npm run build

deploy website:
  stage: deploy
  cache:
    key: site-package
    policy: pull # Get all data from "site-package" key data cache
  # Local "before_script" overwrites the global "before_script"
  before_script:
    - npm install -g surge@^0.21.7
  script:
    - surge --project ./website/build/course-gitlab-ci-cd/ --domain marcellocosta-rc.surge.sh

  # "after_script" always will be executed (even if "script" fails)
  after_script:
    - ls -lsrta

  environment:
    name: staging
    url: http://marcellocosta-rc.surge.sh

  # Runs only in branch "develop" (can use Regex)
  only:
    - develop
